import type { Metadata } from 'next'
import Link from 'next/link'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'FoodCulture AI Privacy Policy',
}

export default function PrivacyPage() {
  const sections = [
    { title: '1. Information we collect', body: 'We collect information you provide directly (name, email, phone, restaurant details), information generated by your use of the Platform (reviews, saved listings, enquiries), and technical information (IP address, browser type, cookies).' },
    { title: '2. How we use your information', body: 'We use your information to provide and improve the Platform, send transactional emails (account verification, listing approval, enquiry notifications), personalise your experience, and comply with legal obligations.' },
    { title: '3. Information sharing', body: 'We do not sell your personal data. We share data with: Supabase (database and authentication), Resend (transactional email), and Vercel (hosting). We may disclose information when required by law.' },
    { title: '4. Restaurant listings and public data', body: 'Restaurant names, cuisine types, and area information listed on the Platform are publicly visible. Personal contact information in enquiries is visible only to the restaurant owner and Platform administrators.' },
    { title: '5. Cookies', body: 'We use strictly necessary cookies for authentication sessions and optional analytics cookies (with your consent). You can manage cookie preferences via the cookie consent banner.' },
    { title: '6. Data retention', body: 'We retain your account data for as long as your account is active. Reviews are anonymised (not deleted) when an account is deleted. Audit logs are retained for 12 months.' },
    { title: '7. Your rights', body: 'You have the right to: access your personal data, correct inaccurate data, request deletion of your account and associated personal data, withdraw consent for optional data processing, and lodge a complaint with a data protection authority.' },
    { title: '8. Account deletion', body: 'You can delete your account at any time from your account settings. This removes your personal profile, saved listings, and notification history. Reviews you have written are anonymised. Some data may be retained in audit logs as required by law.' },
    { title: '9. Security', body: 'We use industry-standard security measures including encrypted connections (HTTPS), Row Level Security on our database, and rate limiting on authentication endpoints. No system is completely secure — use a strong, unique password.' },
    { title: '10. Children', body: 'The Platform is not directed at children under 13. We do not knowingly collect personal data from children.' },
    { title: '11. Changes to this policy', body: 'We may update this Privacy Policy. We will notify you of material changes by email or prominent notice on the Platform.' },
    { title: '12. Contact', body: 'For privacy questions or to exercise your rights, contact us at privacy@foodculture.ai.' },
  ]
  return (
    <div style={{ fontFamily: "-apple-system,sans-serif", background: '#fafafa', minHeight: '100vh', color: '#1a1a1a' }}>
      <Nav />
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px' }}>
        <h1 style={{ fontSize: 28, fontWeight: 700, marginBottom: 8 }}>Privacy Policy</h1>
        <p style={{ fontSize: 14, color: '#888', marginBottom: 32 }}>Last updated: July 2026</p>
        {sections.map(s => (
          <div key={s.title} style={{ marginBottom: 28 }}>
            <h2 style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>{s.title}</h2>
            <p style={{ fontSize: 14, color: '#555', lineHeight: 1.8, margin: 0 }}>{s.body}</p>
          </div>
        ))}
        <div style={{ marginTop: 40, paddingTop: 24, borderTop: '1px solid #ede8e2', fontSize: 13, color: '#aaa' }}>
          <Link href="/terms" style={{ color: '#E85D26', textDecoration: 'none' }}>Terms of Service</Link>
          {' · '}
          <Link href="/account/delete" style={{ color: '#E85D26', textDecoration: 'none' }}>Delete my account</Link>
          {' · '}
          <Link href="/" style={{ color: '#E85D26', textDecoration: 'none' }}>Back to FoodCulture AI</Link>
        </div>
      </div>
      <Footer />
    </div>
  )
}
